name: Quattor
description: Quattor news and documentation
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
exclude: [vendor]
gems:
  - jekyll-feed
  - jekyll-redirect-from
collections:
  development:
    output: true
    permalink: /development/:title.html

